

## Introduction to Hugging Face

Hugging Face provides **state-of-the-art** NLP (and increasingly, multimodal) models and an easy-to-use Python library called **Transformers**. With just a few lines of code you can:

* **Load** pre-trained models for dozens of tasks
* **Run** inference via high-level “pipelines”
* **Fine-tune** on your own data

---

## 1. Setup in Google Colab

```bash
# Install the core libraries
!pip install transformers datasets huggingface_hub --quiet
```

> **Tip:** Colab often comes with a GPU—go to **Runtime → Change runtime type → GPU** for faster inference.

---

## 2. Quick-start with Pipelines

The `pipeline` API wraps tokenization, model loading, and inference in one object.

### 2.1 Sentiment Analysis

```python
from transformers import pipeline

# 1. Load a sentiment-analysis pipeline (defaults to a small model)
sentiment = pipeline("sentiment-analysis")

# 2. Run inference
examples = [
    "Hugging Face makes NLP super accessible!",
    "I dislike bugs in my code..."
]
results = sentiment(examples)
for text, res in zip(examples, results):
    print(f"{text!r:50} → label={res['label']}, score={res['score']:.3f}")
```

### 2.2 Text Generation

```python
from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")
prompt = "Once upon a time"
out = generator(prompt, max_length=30, num_return_sequences=1)
print(out[0]["generated_text"])
```

# Finetuning GPT-2

*In this lab you will work on finetuning GPT 2 to solve specific problems*

- https://www.kaggle.com/code/changyeop/how-to-fine-tune-gpt-2-for-beginners
- https://medium.com/@prashanth.ramanathan/fine-tuning-a-pre-trained-gpt-2-model-and-performing-inference-a-hands-on-guide-57c097a3b810

In [ ]:
# Your Code for recreating these notebooks here



# Use Case-Specific Problems Solvable by Fine-tuning GPT-2 on Custom Documents

Fine-tuning GPT-2 on domain-specific documents enables organizations to create specialized text generation models that address unique business challenges. This report examines several concrete applications where GPT-2 fine-tuning provides effective solutions to industry-specific problems by leveraging custom datasets.

## Domain-Specific Text Generation Applications

### Medical Query Response Systems

The healthcare industry faces significant challenges in providing accessible medical information to patients. Fine-tuning GPT-2 on medical datasets creates specialized models like MedGPT-2 that can address these issues effectively.

MedGPT-2 demonstrates how fine-tuned models can provide accurate responses to medical queries, symptom descriptions, and mental health questions[^5]. This application involves collecting diverse medical datasets from forums and medical websites to train a model capable of generating informative responses to patient questions[^5]. Such systems can reduce the burden on healthcare professionals by serving as a first-line information resource, particularly in underserved areas where medical expertise may be limited.

The implementation process requires careful data collection, model fine-tuning, and integration with user-friendly interfaces like Streamlit for practical deployment[^5]. Future enhancements could include expanding datasets and implementing feedback mechanisms to improve answer quality over time[^5].

### Financial Advisory Services

Financial institutions often struggle to provide personalized advice at scale. Fine-tuned GPT-2 models offer a solution by generating tailored financial guidance based on customer queries.

A financial advice GPT-2 model, fine-tuned on financial datasets, can assist users with budgeting, investment strategies, and financial planning[^7]. This application addresses the need for accessible financial guidance outside traditional advisor relationships. The model leverages the transformer-based architecture of GPT-2 while focusing specifically on financial contexts[^7].

Such models can be integrated into larger financial advisory systems, chatbots, or automated customer service platforms to enhance the financial literacy of customers while reducing operational costs for financial institutions[^7].

### Customer Service Automation

Customer service departments frequently handle repetitive queries that could be automated with appropriate natural language processing systems.

Banking customer service chatbots developed through GPT-2 fine-tuning demonstrate how pre-trained language models can be adapted to specific customer service domains[^6]. By fine-tuning models like distilGPT-2 on banking-related queries and responses, organizations can create conversational AI systems that handle routine customer inquiries effectively[^6].

The implementation process involves tokenizing and preparing datasets, utilizing Hugging Face's Transformers library, and creating user interfaces with tools like Gradio[^6]. These systems can significantly reduce response times and operational costs while maintaining consistent service quality.

### Legal Document Generation

Law firms and legal departments face challenges in drafting standardized legal opinions efficiently while maintaining quality and consistency.

Fine-tuning GPT-2 on legal opinion datasets enables the generation of technical legal reports that follow established formats and incorporate appropriate legal terminology[^4]. This application addresses the time-intensive nature of legal drafting while potentially reducing costs for clients.

Such systems could serve as first-draft generators for attorneys, who would then review and refine the machine-generated content. This workflow maintains quality control while accelerating document production.

## Technical Approaches to Fine-Tuning

### Hierarchical Domain Adaptation

When dealing with related but distinct domains, hierarchical fine-tuning approaches offer advantages over single-domain methods.

Research shows that representing domains hierarchically allows models to capture both domain-specific and general-domain information[^3]. By using adapter layers to represent nodes in a hierarchical structure, models can selectively share representations between related domains while avoiding negative transfer from unrelated domains[^3].

This approach is particularly valuable when fine-tuning for multiple related domains, such as hotel reviews and restaurant reviews, which share some linguistic features but retain domain-specific characteristics[^3]. The hierarchical structure allows upper nodes to be updated more frequently, encoding more general knowledge, while leaf nodes capture domain-specific information[^3].

### Implementation Considerations

Implementing GPT-2 fine-tuning for custom applications involves several critical steps that ensure successful model development.

The process typically begins with installing dependencies and importing necessary libraries, including PyTorch and Hugging Face Transformers[^2]. Data processing involves splitting datasets into training and validation sets (typically 90% for training, 10% for validation)[^2]. Tokenization using the GPT-2 tokenizer prepares input and target sequences with appropriate padding and truncation options[^2].

Training configurations must specify parameters like output directory, number of training epochs, batch size, evaluation strategy, and logging frequency[^2]. After fine-tuning, the model can be saved and deployed for inference, with consideration given to computational resources like GPU availability for optimal performance[^2].

## Application Development Process

### Medical Query Assistant Development

Creating specialized applications like medical query assistants follows a structured process from data collection through deployment.

The development workflow begins with gathering diverse datasets of medical queries and responses from appropriate sources[^5]. After preprocessing the data, the GPT-2 model is fine-tuned using the prepared dataset to adapt it specifically to medical terminology and question-answering patterns[^5].

Following successful fine-tuning, the model is integrated with front-end frameworks like Streamlit to create user-friendly interfaces where users can enter medical queries and receive generated responses[^5]. Backend integration connects the interface to the fine-tuned model, allowing for seamless question processing and answer generation[^5].

### Banking Customer Service Implementation

Building customer service chatbots for specific industries like banking follows similar patterns but with domain-specific considerations.

The development process involves fine-tuning pre-trained models like distilGPT-2 on banking-related conversations and FAQs[^6]. Web-based interfaces created with tools like Gradio allow users to interact with the model through intuitive chat interfaces[^6].

These implementations enable financial institutions to provide 24/7 customer service while maintaining consistent response quality and reducing operational costs[^6].

## Conclusion

Fine-tuning GPT-2 on custom documents presents viable solutions to domain-specific challenges across multiple industries. From healthcare to finance, legal services to customer support, the ability to adapt pre-trained language models to specialized domains creates opportunities for automation, improved service delivery, and cost reduction.

The success of these applications depends on carefully selected training data, appropriate fine-tuning methodologies, and thoughtful integration into existing workflows. As organizations continue to explore the potential of fine-tuned language models, we can expect to see increasingly sophisticated applications that address more complex domain-specific problems.

Future developments will likely focus on improving model accuracy, expanding datasets to cover more diverse scenarios, and implementing feedback mechanisms that allow fine-tuned models to improve continuously through real-world use.


[^1]: https://platform.openai.com/docs/guides/fine-tuning

[^2]: https://github.com/arham-kk/gpt2-finetune

[^3]: https://blog.allenai.org/efficient-hierarchical-domain-adaptation-using-pretrained-language-models-fdd04c001230?gi=0c070ef42bb7

[^4]: https://community.openai.com/t/is-fine-tuning-the-way-to-go-to-generate-legal-opinions-law-technical-reports/170169

[^5]: https://github.com/Saish459/Finetuning-LLMs-MedGPT

[^6]: https://www.youtube.com/watch?v=_Pndmc__-v4

[^7]: https://huggingface.co/RoamifyMML/financial-advice-gpt2

[^8]: https://github.com/MehwishFatimah/GPT2_Summarization

[^9]: https://www.restack.io/p/fine-tuning-answer-gpt2-cat-ai

[^10]: https://30dayscoding.com/blog/gpt-for-named-entity-recognition-and-entity-extraction

[^11]: https://www.youtube.com/watch?v=nsdCRVuprDY

[^12]: https://community.openai.com/t/fine-tuning-gpt2-with-gpt4-responses-is-it-allowed/326740

[^13]: https://github.com/lizatukhtina/fine-tune-gpt2-for-meetiing-summarization

[^14]: https://www.toptal.com/deep-learning/exploring-pre-trained-models

[^15]: https://www.cohorte.co/blog/fine-tuning-gpt-2-with-hugging-face-transformers-a-complete-guide

[^16]: https://www.linkedin.com/pulse/fine-tuning-gpt-2-large-language-model-unlocking-its-adamson-mbcs

[^17]: https://drlee.io/fine-tuning-gpt-2-for-sentiment-analysis-94ebdd7b5b24

[^18]: https://blog.devgenius.io/fine-tuning-the-gpt-2-large-language-model-unlocking-its-full-potential-66e3a082ab9c?gi=4773a5eba121

[^19]: https://fxis.ai/edu/how-to-fine-tune-the-gpt-2-model-for-specific-tasks/

[^20]: https://www.youtube.com/watch?v=2bqjzUX9ssE

[^21]: https://ar5iv.labs.arxiv.org/html/2112.08718

[^22]: https://fxis.ai/edu/how-to-fine-tune-the-gpt-2-model-a-comprehensive-guide-2/

[^23]: https://github.com/vaddhiparthy/GPT

[^24]: https://www.restack.io/p/transfer-learning-answer-gpt2-transfer-learning-cat-ai

[^25]: https://fxis.ai/edu/how-to-fine-tune-gpt-2-a-step-by-step-guide/

[^26]: https://fxis.ai/edu/how-to-fine-tune-a-gpt-2-model-on-a-custom-dataset/

[^27]: http://arxiv.org/pdf/2112.08718.pdf

[^28]: https://openai.com/index/fine-tuning-gpt-2/

[^29]: https://www.linkedin.com/pulse/part-2a-fine-tuning-gpt-2-harry-potter-language-generation-mehta-3m7lc

[^30]: https://itnext.io/easily-build-your-own-gpt-from-scratch-using-aws-51811b6355d3

[^31]: https://www.restack.io/p/fine-tuning-gpt-2-answer-techniques-cat-ai

[^32]: https://www.toolify.ai/ai-news/mastering-gpt2-finetuning-python-guide-for-llm-finetuning-588131

[^33]: https://www.linkedin.com/pulse/legal-drafting-ai-putting-gpt-2-practical-use-sergii-shcherbak

[^34]: https://ouci.dntb.gov.ua/en/works/4OoXnJ24/

[^35]: https://deepdesk.com/blog/gpt-and-customer-service

[^36]: https://huggingface.co/RoamifyMML/financial-advice-gpt2/blob/46c97bb80d0a6d886e30748fa20d7d3d42ec3f58/README.md

[^37]: https://www.youtube.com/watch?v=oEpLMb5D_G0

[^38]: https://scholars.lib.ntu.edu.tw/entities/publication/329d6f25-8778-4bd9-a9ab-7d9952e29d53

[^39]: https://www.linkedin.com/posts/shakti-pawar_fundamentals-finetuning-gpt2-on-medical-activity-7251144314393677825-9Zul

[^40]: https://www.linkedin.com/posts/manoj-ajjakana_building-a-customer-service-chatbot-with-activity-7241433202525937665-j0kV

[^41]: https://blog.aryansingh.space/blog/Fine-Tuning-GPT-2-for-Financial-News-and-Analysis-Text-Generation

[^42]: https://github.com/Jayveersinh-Raj/code_generation_gpt2

[^43]: https://www.intel.com/content/www/us/en/developer/articles/training/fine-tuning-gpt2-with-hugging-face-and-intel-gaudi.html

[^44]: https://github.com/aymanehachcham/GPT2_Text_Summarization

[^45]: https://sohaib.com/how-to-use-gpt2-for-question-answering/

[^46]: https://30dayscoding.com/blog/fine-tuning-gpt-for-relation-extraction-and-knowledge-base-population

[^47]: https://discuss.huggingface.co/t/fine-tuning-gpt2-for-question-answering/31895

[^48]: https://arxiv.org/pdf/2309.06112.pdf

[^49]: https://www.linkedin.com/pulse/crafting-coherent-contextually-relevant-text-gpt-2-technical-arora-anfoc

[^50]: https://github.com/omidiu/GPT-2-Fine-Tuning

[^51]: https://www.youtube.com/watch?v=C_pWDlZWNIE

[^52]: https://github.com/arham-kk/gpt2-finetune

[^53]: https://discuss.huggingface.co/t/how-to-train-gpt-2-for-text-summarization/31731

[^54]: https://blog.paperspace.com/generating-text-summaries-gpt-2/

[^55]: https://www.restack.io/p/fine-tune-gpt2-answer-summarization-cat-ai

[^56]: https://www.cohorte.co/blog/fine-tuning-gpt-2-with-hugging-face-transformers-a-complete-guide

# Problems

Below are practical problems that can be addressed by fine-tuning GPT-2 on publicly available datasets, along with a brief overview of how to solve each using Google Colab.

---

### 1. Sentiment Analysis on Movie Reviews

**Problem:**  
Automatically classify movie reviews as positive or negative.

**Public Data:**  
IMDb movie reviews dataset (available via Hugging Face Datasets library).

**How to Solve:**
- Load the IMDb dataset using `datasets.load_dataset("imdb")`[3][5].
- Preprocess and tokenize the reviews using GPT-2’s tokenizer.
- Fine-tune GPT-2 (or GPT-2 for sequence classification) for 2–3 epochs on a Colab GPU instance.
- Evaluate the model and use it to predict sentiment for new reviews[3][5].

---

### 2. Domain-Specific Text Generation (e.g., Harry Potter Fan Fiction)

**Problem:**  
Generate creative text in the style of a specific domain, such as Harry Potter fan fiction.

**Public Data:**  
Fan fiction or book excerpts from Project Gutenberg or fan sites.

**How to Solve:**
- Gather and clean a collection of relevant text (e.g., Harry Potter books or fan fiction)[4].
- Tokenize the text using GPT-2’s tokenizer.
- Fine-tune GPT-2 for language modeling (text generation) for several epochs.
- Use the model to generate new domain-specific stories or paragraphs[4].

---

### 3. FAQ Answer Generation for a Public Dataset

**Problem:**  
Automatically generate answers to frequently asked questions in a specific domain (e.g., COVID-19 FAQs, Stack Overflow programming questions).

**Public Data:**  
- COVID-19 FAQ datasets from official sources.
- Stack Overflow question-answer pairs (public data dumps).

**How to Solve:**
- Collect question-answer pairs and clean the dataset[1].
- Format data as prompt-response pairs for GPT-2.
- Tokenize and fine-tune GPT-2 on these pairs.
- Use the model to generate answers to new, similar questions[1].

---

### 4. Headline Generation for News Articles

**Problem:**  
Generate concise headlines for news articles.

**Public Data:**  
CNN/DailyMail news dataset or other open news datasets.

**How to Solve:**
- Download and preprocess article-headline pairs.
- Tokenize the data and fine-tune GPT-2 to generate headlines given article snippets.
- Evaluate model outputs on a validation set.

---

### 5. Poetry or Song Lyric Generation

**Problem:**  
Generate poetry or song lyrics in a particular style.

**Public Data:**  
Poetry Foundation corpus, Project Gutenberg poetry, or song lyrics datasets.

**How to Solve:**
- Gather and clean a corpus of poems or lyrics.
- Tokenize and fine-tune GPT-2 for text generation.
- Prompt the model with a first line or theme to generate new poetic content.

---

## General Steps for Fine-Tuning on Google Colab

1. **Set Up Colab and Enable GPU:**  
   Open a new Colab notebook, enable GPU support[2].

2. **Install Required Libraries:**  
   Install `transformers`, `torch`, and `datasets`[2][3][5].

3. **Load and Preprocess Data:**  
   Use Hugging Face Datasets or upload your own data. Clean and tokenize the text[1][3][5].

4. **Load Pre-trained GPT-2 Model:**  
   Use `GPT2LMHeadModel` for generation or `GPT2ForSequenceClassification` for classification tasks[3][5].

5. **Fine-Tune the Model:**  
   Use Hugging Face’s `Trainer` or a custom training loop. Set epochs and batch size to fit within Colab’s memory and time constraints[3][5].

6. **Evaluate and Save the Model:**  
   Test the model on a validation set and save it to Google Drive or download it[2][3].

---


Citations:
[1] https://www.restack.io/p/fine-tuning-answer-gpt-2-models-cat-ai
[2] https://www.reddit.com/r/learnmachinelearning/comments/1fm6gif/is_it_possible_to_finetune_pretrained_models_like/
[3] https://drlee.io/fine-tuning-gpt-2-for-sentiment-analysis-94ebdd7b5b24
[4] https://www.linkedin.com/pulse/part-2a-fine-tuning-gpt-2-harry-potter-language-generation-mehta-3m7lc
[5] https://www.cohorte.co/blog/fine-tuning-gpt-2-with-hugging-face-transformers-a-complete-guide
[6] https://labelyourdata.com/articles/gpt-fine-tuning
[7] https://customgpt.ai/openai-gpt-fine-tuning-cases/
[8] https://github.com/DivyanshTiwari20/fine-tunning-GPT2LMHeadModel
[9] https://drlee.io/fine-tuning-gpt-2-for-sentiment-analysis-94ebdd7b5b24
[10] https://www.datacamp.com/tutorial/fine-tuning-large-language-models
[11] https://www.restack.io/p/fine-tuning-answer-gpt-2-cat-ai
[12] https://www.linkedin.com/pulse/part-2a-fine-tuning-gpt-2-harry-potter-language-generation-mehta-3m7lc
[13] https://www.restack.io/p/fine-tuning-gpt-2-answer-techniques-cat-ai
[14] https://github.com/arham-kk/gpt2-finetune
[15] https://gist.github.com/MattPitlyk/45541145ad48b93da395f0a72ec2e7dc?short_path=2ad537e
[16] https://colab.research.google.com/github/philschmid/fine-tune-GPT-2/blob/master/Fine_tune_a_non_English_GPT_2_Model_with_Huggingface.ipynb
[17] https://www.youtube.com/watch?v=2bqjzUX9ssE
[18] https://platform.openai.com/docs/guides/fine-tuning
[19] https://github.com/openai/gpt-2/issues/155
[20] https://www.youtube.com/watch?v=nsdCRVuprDY
[21] https://www.toptal.com/deep-learning/exploring-pre-trained-models
[22] https://www.youtube.com/watch?v=C_pWDlZWNIE
[23] https://www.toolify.ai/gpts/level-up-your-nlp-finetune-llama-2-model-with-free-colab-326769
[24] https://colab.research.google.com/drive/13dZVYEOMhXhkXWfvSMVM1TTtUDrT6Aeh?usp=sharing
[25] https://www.kaggle.com/code/changyeop/how-to-fine-tune-gpt-2-for-beginners
[26] https://stackoverflow.com/questions/74712335/how-to-fine-tune-a-gpt-2-model

# **Problem 1:** Sentiment Analysis on Movie Reviews

In [7]:
!pip install -U -q evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.5 MB/s eta 0:00:00

# **Problem 1: Sentiment Analysis on Movie Reviews**

In [8]:
# ==========================================================
# Sentiment Analysis on Movie Reviews — Fine-tune GPT-2
# Dataset: IMDb (Hugging Face Datasets)
#   !pip install -U -q datasets huggingface_hub fsspec transformers accelerate evaluate


import numpy as np
import torch

# Force the datasets library to skip its torchvision integration.
# torchvision isn't used anywhere in this text-classification script, but
# datasets auto-detects it and tries to import VideoReader from it, which
# breaks on newer torchvision versions where VideoReader was removed.
# Setting this flag before importing datasets avoids that broken code path.
import datasets.config
datasets.config.TORCHVISION_AVAILABLE = False

from datasets import load_dataset
from transformers import (
    GPT2Tokenizer,
    GPT2ForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding,
)
import evaluate

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# ==========================================================
# 1. Load the IMDb dataset
# ==========================================================
raw_datasets = load_dataset("stanfordnlp/imdb")
print(raw_datasets)


train_dataset = raw_datasets["train"].shuffle(seed=42).select(range(5000))
test_dataset = raw_datasets["test"].shuffle(seed=42).select(range(2000))

# ==========================================================
# 2. Tokenizer — GPT-2 has no pad token by default, so we add one
# ==========================================================
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token  # GPT-2 fix: reuse eos as pad

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=256,  # movie reviews can be long; 256 keeps training fast
    )

tokenized_train = train_dataset.map(tokenize_function, batched=True)
tokenized_test = test_dataset.map(tokenize_function, batched=True)

# Remove the raw text column, rename label -> labels (Trainer expects "labels")
tokenized_train = tokenized_train.remove_columns(["text"])
tokenized_test = tokenized_test.remove_columns(["text"])
tokenized_train = tokenized_train.rename_column("label", "labels")
tokenized_test = tokenized_test.rename_column("label", "labels")
tokenized_train.set_format("torch")
tokenized_test.set_format("torch")

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# ==========================================================
# 3. Load GPT-2 for sequence classification (binary: pos/neg)
# ==========================================================
model = GPT2ForSequenceClassification.from_pretrained(
    "gpt2",
    num_labels=2,
    id2label={0: "NEGATIVE", 1: "POSITIVE"},
    label2id={"NEGATIVE": 0, "POSITIVE": 1},
)
# GPT-2's classification head needs to know the pad token id
model.config.pad_token_id = tokenizer.pad_token_id
model.to(device)

# ==========================================================
# 4. Metrics
# ==========================================================
accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    acc = accuracy_metric.compute(predictions=predictions, references=labels)
    f1 = f1_metric.compute(predictions=predictions, references=labels)
    return {"accuracy": acc["accuracy"], "f1": f1["f1"]}

# ==========================================================
# 5. Training arguments and Trainer
# ==========================================================
training_args = TrainingArguments(
    output_dir="./gpt2-imdb-sentiment",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=50,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    fp16=torch.cuda.is_available(),  # mixed precision if on GPU
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# ==========================================================
# 6. Fine-tune
# ==========================================================
trainer.train()

# ==========================================================
# 7. Evaluate on the test set
# ==========================================================
eval_results = trainer.evaluate()
print("Final evaluation results:", eval_results)

# ==========================================================
# 8. Save the fine-tuned model
# ==========================================================
trainer.save_model("./gpt2-imdb-sentiment/final")
tokenizer.save_pretrained("./gpt2-imdb-sentiment/final")

# ==========================================================
# 9. Run inference on new, unseen reviews
# ==========================================================
def predict_sentiment(text, model, tokenizer, device):
    model.eval()
    inputs = tokenizer(
        text, return_tensors="pt", truncation=True, max_length=256
    ).to(device)
    with torch.no_grad():
        logits = model(**inputs).logits
    probs = torch.softmax(logits, dim=-1).squeeze()
    pred_id = int(torch.argmax(probs))
    label = model.config.id2label[pred_id]
    confidence = float(probs[pred_id])
    return label, confidence

sample_reviews = [
    "This movie was an absolute masterpiece, the acting and cinematography blew me away.",
    "Terrible plot, wooden acting, and a complete waste of two hours.",
    "It was okay, not great but not bad either, some parts dragged on.",
]

print("\n--- Sample predictions ---")
for review in sample_reviews:
    label, conf = predict_sentiment(review, model, tokenizer, device)
    print(f"Review: {review[:60]}...")
    print(f"  -> Predicted: {label} (confidence: {conf:.3f})\n")

Using device: cuda

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

plain_text/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 21.0MB

plain_text/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

plain_text/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 20.5MB

plain_text/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

plain_text/unsupervised-00000-of-00001.p(…): reconstructing file:   0%|          |  0.00B / 42.0MB

plain_text/unsupervised-00000-of-00001.p(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] GPT2ForSequenceClassification LOAD REPORT from: gpt2
Key          | Status  |
-------------+---------+-
score.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Final evaluation results: {'eval_loss': 0.3590351641178131, 'eval_accuracy': 0.9145, 'eval_f1': 0.9153046062407132}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

--- Sample predictions ---
Review: This movie was an absolute masterpiece, the acting and cinem...
  -> Predicted: POSITIVE (confidence: 0.966)

Review: Terrible plot, wooden acting, and a complete waste of two ho...
  -> Predicted: NEGATIVE (confidence: 0.999)

Review: It was okay, not great but not bad either, some parts dragge...
  -> Predicted: NEGATIVE (confidence: 0.931)

# Problem 2:Domain-Specific Text Generation (e.g., Harry Potter Fan Fiction)

In [9]:
import urllib.request
url = "https://www.gutenberg.org/cache/epub/55/pg55.txt"
raw = urllib.request.urlopen(url).read().decode("utf-8")
start = raw.find("*** START OF")
start = raw.find("\n", start) + 1
end = raw.find("*** END OF")
story_text = raw[start:end].strip()
with open("my_corpus.txt", "w", encoding="utf-8") as f:
    f.write(story_text)
print(f"Saved {len(story_text)} characters to my_corpus.txt")

Saved 212568 characters to my_corpus.txt

In [10]:
# ==========================================================
# Domain-Specific Text Generation — Fine-tune GPT-2 for language modeling
#
# This script fine-tunes GPT-2 on a plain-text corpus you provide, so it
# generates new text in that corpus's style (fan fiction, a specific
# author's voice, a genre, etc.).

#   !pip install -U -q datasets huggingface_hub fsspec transformers accelerate evaluate
import math
import torch
import datasets.config
datasets.config.TORCHVISION_AVAILABLE = False

from datasets import load_dataset
from transformers import (
    GPT2Tokenizer,
    GPT2LMHeadModel,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# 0. Point this at your own corpus file
CORPUS_PATH = "my_corpus.txt"  # <-- upload your .txt file in Colab's file browser and update this path

# 1. Load the text file as a Hugging Face dataset
raw_datasets = load_dataset("text", data_files={"train": CORPUS_PATH})

# Split off a small validation set so we can track overfitting
split_datasets = raw_datasets["train"].train_test_split(test_size=0.05, seed=42)
print(split_datasets)

# 2. Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token

BLOCK_SIZE = 256  # sequence length per training example

def tokenize_function(examples):
    return tokenizer(examples["text"])

tokenized_datasets = split_datasets.map(
    tokenize_function, batched=True, remove_columns=["text"]
)

# Concatenate all tokenized text, then chop into fixed-length blocks.
# This is the standard approach for language-model fine-tuning: rather than
# padding every short line, we pack tokens end-to-end so training is efficient.
def group_texts(examples):
    concatenated = sum(examples["input_ids"], [])
    total_length = (len(concatenated) // BLOCK_SIZE) * BLOCK_SIZE
    result_ids = [
        concatenated[i : i + BLOCK_SIZE] for i in range(0, total_length, BLOCK_SIZE)
    ]
    return {"input_ids": result_ids, "labels": [ids.copy() for ids in result_ids]}

lm_datasets = tokenized_datasets.map(
    group_texts,
    batched=True,
    remove_columns=tokenized_datasets["train"].column_names,
)
lm_datasets.set_format("torch")

# For causal LM, the collator just needs to know we're NOT doing masked LM
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# 3. Load GPT-2 for language modeling
model = GPT2LMHeadModel.from_pretrained("gpt2")
model.to(device)

# 4. Training arguments and Trainer
training_args = TrainingArguments(
    output_dir="./gpt2-domain-generator",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=50,
    load_best_model_at_end=True,
    fp16=torch.cuda.is_available(),
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=lm_datasets["train"],
    eval_dataset=lm_datasets["test"],
    processing_class=tokenizer,
    data_collator=data_collator,
)

# 5. Fine-tune
trainer.train()

# 6. Evaluate — report perplexity, the standard LM quality metric
eval_results = trainer.evaluate()
perplexity = math.exp(eval_results["eval_loss"])
print(f"Final eval loss: {eval_results['eval_loss']:.4f}")
print(f"Perplexity: {perplexity:.2f}  (lower is better)")

# 7. Save the fine-tuned model
trainer.save_model("./gpt2-domain-generator/final")
tokenizer.save_pretrained("./gpt2-domain-generator/final")

# 8. Generate new text in the fine-tuned style
def generate_text(
    prompt,
    model,
    tokenizer,
    device,
    max_new_tokens=150,
    temperature=0.9,
    top_p=0.92,
    top_k=50,
    num_return_sequences=1,
):
    model.eval()
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            top_p=top_p,
            top_k=top_k,
            num_return_sequences=num_return_sequences,
            pad_token_id=tokenizer.eos_token_id,
        )
    return [tokenizer.decode(o, skip_special_tokens=True) for o in outputs]

prompt = "The castle grounds were quiet that morning, until"
generated = generate_text(prompt, model, tokenizer, device, num_return_sequences=2)

print("\n--- Generated samples ---")
for i, text in enumerate(generated, 1):
    print(f"\nSample {i}:\n{text}")

Using device: cuda

Generating train split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 4514
    })
    test: Dataset({
        features: ['text'],
        num_rows: 238
    })
})

Map:   0%|          | 0/4514 [00:00<?, ? examples/s]

Map:   0%|          | 0/238 [00:00<?, ? examples/s]

Map:   0%|          | 0/4514 [00:00<?, ? examples/s]

Map:   0%|          | 0/238 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Final eval loss: 3.4628
Perplexity: 31.91  (lower is better)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

--- Generated samples ---

Sample 1:
The castle grounds were quiet that morning, until at last they heard a clang of the wheels of a truck and stopped. The Tin Woodman said, “But they don’t like your brains,” he added. “They“Are we in a bad place,” exclaimed the girl, “and I think wewill find you’s room. “What is the matter,” asked the little girl, “for you are so dangerous?”“But,” asked the Scarecrow, “they have plenty of brains. They know all that is true about brains,” she replied. “That is why we are called“Oh, yes!” exclaimed the girl; and she

Sample 2:
The castle grounds were quiet that morning, until Toto and Toto saw a wildcat coming into sight, and after a short moment of hesitation said to the Lion, “Oh!”“We can carry you to a“That’s right,” said the Woodman, “for we are not travelers; but if you will come to me, I shall send you back to Kansas, where you will meet the Wizard who saved Toto.”the Wicked Witch of the West, Chapter I. The Woodman, as Good as he Was, and as Good as he was, gave no other orders.for they had“They haven’t thought of it,” replied the Tin Woodman, “but I thought

# Problem 3: FAQ Answer Generation for a Public Dataset

In [11]:
# ==========================================================
# FAQ / Q&A Generation — Fine-tune GPT-2 on question-answer pairs
#
# Fine-tunes GPT-2 so that given "Question: <text>\nAnswer:" it generates
# a plausible answer, learned from a dataset of real Q&A pairs.
#
# This script uses the COVID-19 QA dataset (deepset/covid_qa_deepset) from
# the Hugging Face Hub as the public data source — real questions and
# answers extracted from official COVID-19 research papers. Swap the
# dataset name in step 1 to use a different domain (e.g. a Stack Overflow
# Q&A dump) if you'd prefer.
#   !pip install -U -q datasets huggingface_hub fsspec transformers accelerate evaluate
# ==========================================================

import math
import torch

# Skip datasets' broken torchvision integration (unrelated to this task,
# but avoids a common ImportError in Colab environments).
import datasets.config
datasets.config.TORCHVISION_AVAILABLE = False

from datasets import load_dataset
from transformers import (
    GPT2Tokenizer,
    GPT2LMHeadModel,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# 1. Load a question-answer dataset
raw_datasets = load_dataset("deepset/covid_qa_deepset")
print(raw_datasets)
print(raw_datasets["train"][0])  # inspect the fields: question, answers, context, ...

# The 'answers' field is a dict like {"text": [...], "answer_start": [...]}.
# We pull out the first answer text for each example.
def extract_answer(example):
    example["answer_text"] = example["answers"]["text"][0]
    return example

raw_datasets = raw_datasets.map(extract_answer)

# Keep only the columns we need, split into train/validation
raw_datasets = raw_datasets["train"].select_columns(["question", "answer_text"])
split_datasets = raw_datasets.train_test_split(test_size=0.05, seed=42)
print(split_datasets)

# 2. Format each example as a single prompt-response training string
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token

def format_qa(example):
    text = f"Question: {example['question']}\nAnswer: {example['answer_text']}{tokenizer.eos_token}"
    return {"text": text}

formatted_datasets = split_datasets.map(format_qa, remove_columns=["question", "answer_text"])

# 3. Tokenize
MAX_LENGTH = 256

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length",
    )

tokenized_datasets = formatted_datasets.map(
    tokenize_function, batched=True, remove_columns=["text"]
)
tokenized_datasets.set_format("torch")

# Causal LM collator — labels are the input_ids themselves, shifted
# internally by the model during loss computation
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# ==========================================================
# 4. Load GPT-2 for language modeling
# ==========================================================
model = GPT2LMHeadModel.from_pretrained("gpt2")
model.to(device)

# ==========================================================
# 5. Training arguments and Trainer
# ==========================================================
training_args = TrainingArguments(
    output_dir="./gpt2-faq-generator",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=50,
    load_best_model_at_end=True,
    fp16=torch.cuda.is_available(),
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    processing_class=tokenizer,
    data_collator=data_collator,
)

# ==========================================================
# 6. Fine-tune
# ==========================================================
trainer.train()

# ==========================================================
# 7. Evaluate — perplexity
# ==========================================================
eval_results = trainer.evaluate()
perplexity = math.exp(eval_results["eval_loss"])
print(f"Final eval loss: {eval_results['eval_loss']:.4f}")
print(f"Perplexity: {perplexity:.2f}  (lower is better)")

# ==========================================================
# 8. Save the fine-tuned model
# ==========================================================
trainer.save_model("./gpt2-faq-generator/final")
tokenizer.save_pretrained("./gpt2-faq-generator/final")

# ==========================================================
# 9. Ask new questions
# ==========================================================
def answer_question(
    question,
    model,
    tokenizer,
    device,
    max_new_tokens=80,
    temperature=0.7,
    top_p=0.9,
):
    model.eval()
    prompt = f"Question: {question}\nAnswer:"
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            top_p=top_p,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )
    full_text = tokenizer.decode(output[0], skip_special_tokens=True)
    # Return just the generated answer portion
    return full_text.split("Answer:", 1)[-1].strip()

sample_questions = [
    "What are the common symptoms of COVID-19?",
    "How does COVID-19 spread between people?",
    "What is the incubation period for COVID-19?",
]

print("\n--- Sample generated answers ---")
for q in sample_questions:
    answer = answer_question(q, model, tokenizer, device)
    print(f"\nQ: {q}\nA: {answer}")

Using device: cuda
DatasetDict({
    train: Dataset({
        features: ['document_id', 'context', 'question', 'is_impossible', 'id', 'answers'],
        num_rows: 2019
    })
})

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Final eval loss: 2.7650
Perplexity: 15.88  (lower is better)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

--- Sample generated answers ---

Q: What are the common symptoms of COVID-19?
A: fever, cough, or wheeze, with or without fever and/or wheezing symptoms, followed by weakness, weakness, or death within a week or two of onset, followed by cough, or wheeze, with or without fever and/or wheezing symptoms. Fever, cough, or wheeze with or without fever and/or cough and/or wheeze

Q: How does COVID-19 spread between people?
A: by coughing and sneezing, or by airway inflammatory diseases such as adenovirus, respiratory syncytial virus, enterovirus, hepatitis, and enterovirus pneumonia. In severe cases, coughing and sneezing may also result in death and may also lead to severe exacerbations in the airway. The cough and sneezing may also lead to severe exacerbations in

Q: What is the incubation period for COVID-19?
A: incubation period of up to 30 days (Pt) and incubation period of up to 5 days (Pt) of COVID-19 infection in a population of 7 to 15 years old. The incubation period is 5 to 10 days in most cases, and the incubation period is 4 to 5 days in most cases. The incubation period for COVID-19 infection in humans

# Problem 4:  Headline Generation for News Articles

In [13]:
# ==========================================================
# News Headline Generation — Fine-tune GPT-2 on article-headline pairs
#
# Fine-tunes GPT-2 so that given "Article: <snippet>\nHeadline:" it
# generates a concise headline, learned from the CNN/DailyMail dataset.
#
# NOTE on the data: CNN/DailyMail's "highlights" field is actually a short
# multi-sentence bullet-point summary, not a single-line headline in the
# strict sense. It's the standard public dataset used for this kind of
# task and works well for "concise headline/summary generation" - just be
# aware the outputs will look more like 1-3 sentence summaries than
# newspaper-style headlines. If you want stricter single-line headlines,
# you can truncate 'highlights' to its first sentence (shown below).

!pip install -U -q datasets huggingface_hub fsspec transformers accelerate evaluate rouge_score
# ==========================================================

import math
import torch
import datasets.config
datasets.config.TORCHVISION_AVAILABLE = False

from datasets import load_dataset
from transformers import (
    GPT2Tokenizer,
    GPT2LMHeadModel,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)
import evaluate

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# ==========================================================
# 1. Load the CNN/DailyMail dataset
# ==========================================================
raw_datasets = load_dataset("abisee/cnn_dailymail", "3.0.0")
print(raw_datasets)
print(raw_datasets["train"][0]["article"][:300])
print("---")
print(raw_datasets["train"][0]["highlights"])

train_dataset = raw_datasets["train"].shuffle(seed=42).select(range(8000))
val_dataset = raw_datasets["validation"].shuffle(seed=42).select(range(1000))

# ==========================================================
# 2. Format each example as a single prompt-response training string
# ==========================================================
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token

ARTICLE_SNIPPET_CHARS = 800  # how much of the article to feed as context

def format_example(example):
    snippet = example["article"][:ARTICLE_SNIPPET_CHARS]
    headline = example["highlights"].strip()
    text = f"Article: {snippet}\nHeadline: {headline}{tokenizer.eos_token}"
    return {"text": text, "headline_ref": headline, "article_snippet": snippet}

train_formatted = train_dataset.map(format_example, remove_columns=raw_datasets["train"].column_names)
val_formatted = val_dataset.map(format_example, remove_columns=raw_datasets["train"].column_names)

val_references = val_formatted["headline_ref"]
val_article_snippets = val_formatted["article_snippet"]

# ==========================================================
# 3. Tokenize
# ==========================================================
MAX_LENGTH = 384

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length",
    )

train_tokenized = train_formatted.map(
    tokenize_function, batched=True, remove_columns=["text", "headline_ref", "article_snippet"]
)
val_tokenized = val_formatted.map(
    tokenize_function, batched=True, remove_columns=["text", "headline_ref", "article_snippet"]
)
train_tokenized.set_format("torch")
val_tokenized.set_format("torch")

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# ==========================================================
# 4. Load GPT-2 for language modeling
# ==========================================================
model = GPT2LMHeadModel.from_pretrained("gpt2")
model.to(device)

# ==========================================================
# 5. Training arguments and Trainer
# ==========================================================
training_args = TrainingArguments(
    output_dir="./gpt2-headline-generator",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=50,
    load_best_model_at_end=True,
    fp16=torch.cuda.is_available(),
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    processing_class=tokenizer,
    data_collator=data_collator,
)

# ==========================================================
# 6. Fine-tune
# ==========================================================
trainer.train()

# ==========================================================
# 7. Evaluate — perplexity (LM quality)
# ==========================================================
eval_results = trainer.evaluate()
perplexity = math.exp(eval_results["eval_loss"])
print(f"Final eval loss: {eval_results['eval_loss']:.4f}")
print(f"Perplexity: {perplexity:.2f}  (lower is better)")

# ==========================================================
# 8. Save the fine-tuned model
# ==========================================================
trainer.save_model("./gpt2-headline-generator/final")
tokenizer.save_pretrained("./gpt2-headline-generator/final")

# ==========================================================
# 9. Generate headlines and score them with ROUGE
# ==========================================================
def generate_headline(
    article_snippet,
    model,
    tokenizer,
    device,
    max_new_tokens=40,
    temperature=0.7,
    top_p=0.9,
):
    model.eval()
    prompt = f"Article: {article_snippet}\nHeadline:"
    inputs = tokenizer(
        prompt, return_tensors="pt", truncation=True, max_length=MAX_LENGTH
    ).to(device)
    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            top_p=top_p,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )
    full_text = tokenizer.decode(output[0], skip_special_tokens=True)
    return full_text.split("Headline:", 1)[-1].strip()

# Generate headlines for a handful of validation articles and compute ROUGE
rouge_metric = evaluate.load("rouge")

NUM_EVAL_SAMPLES = 50
predictions = []
references = []

for i in range(min(NUM_EVAL_SAMPLES, len(val_article_snippets))):
    pred = generate_headline(val_article_snippets[i], model, tokenizer, device)
    predictions.append(pred)
    references.append(val_references[i])

rouge_results = rouge_metric.compute(predictions=predictions, references=references)
print("\n--- ROUGE scores on validation sample ---")
for key, value in rouge_results.items():
    print(f"{key}: {value:.4f}")

print("\n--- Example generated headlines vs. reference ---")
for i in range(5):
    print(f"\nGenerated: {predictions[i]}")
    print(f"Reference: {references[i]}")

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 38.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 793.2/793.2 kB 53.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.9/203.9 kB 21.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 114.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 124.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 17.5 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.6.0 which is incompatible.
Using device: cuda
DatasetDict({
    train: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 287113
    })
    validation: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 13368
    })
    test: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 11490
    })
})
LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappoi
---
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday .
Young actor says he has no plans to fritter his cash away .
Radcliffe's earnings from first five Potter films have been held in trust fund .

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Final eval loss: 2.7221
Perplexity: 15.21  (lower is better)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

--- ROUGE scores on validation sample ---
rouge1: 0.3153
rouge2: 0.1210
rougeL: 0.2289
rougeLsum: 0.2957

--- Example generated headlines vs. reference ---

Generated: Jarryd Hayne has signed with the San Francisco 49ers .
He is an exceptional athlete .
Peter Illfield, chairman of US Association of Rugby League, said: 'Jarryd
Reference: Jarryd Hayne quit the NRL in October to try and get into American Football .
This week, he signed a three-year contract with the San Francisco 49ers .
The chairman of the US Association of Rugby League welcomed his arrival .

Generated: Faith March, 18, from Maldon, Essex, was suffering from anorexia after she dropped to 5 stone .
Her weight dropped to just five stone after the illness but she is now at
Reference: Faith March's dropped to just five stone as she suffered from anorexia .
The 18-year-old from Essex was living on just coffee and no food .
After she collapsed in the bathroom, she had hospital treatment .
Has now launched a patisserie business to help her recover .

Generated: "Community's" sixth season made its debut Tuesday .
It's a departure from previous seasons, but it's a welcome one .
It's a departure from the series' core premise, which
Reference: The fan favorite comedy "Community" returns for a sixth season on Yahoo .
The series is just as weirdly hilarious as ever, with surprises in store .
Critics and fans loved the premiere .

Generated: Sean and his girlfriend, Cassandra Fairbanks, found the man in Los Angeles on Saturday .
He has since been tracked down, and now has a Facebook page .
He is pictured smiling and b
Reference: Dancing Man humiliated by bullies who posted two photos of him online .
In one image, he was seen dancing enthusiastically to music at concert .
In other, he was bowing head, ashamed, after the bullies laughed at him .
'Spotted this specimen trying to dance the other week,' cameraman said .
Images, initially posted to 4chan, were spotted by Cassandra Fairbanks .
She tweeted them on Thursday, asking users to help her to identify man .
On Friday morning, he was successfully identified as Sean from London .
Now, he has been sent VIP invite to dance party in LA with 1,727 women .

Generated: A fraternity video shows two Oklahoma high school football players making racist comments .
The video shows Rice and Pettit shouting racial slurs and laughing .
The fraternity is now under fire after the video surfaced .
Reference: "That video does not represent his core personality,"  a friend of Parker Rice says .
Levi Pettit, the second student expelled,  mainly focused on college football on social media .

# **Problem 5: Poetry or Song Lyric Generation**

In [16]:
poetry_text = """
The moon shines softly over the quiet night.
Stars are dancing across the endless sky.
The wind moves gently through the trees.
Dreams travel quietly beyond the mountains.

The morning sun rises over the golden hills.
Birds sing softly in the peaceful garden.
A new day begins with hope and light.
The world wakes slowly beneath the morning sky.

The river flows beneath the silver moon.
The mountains stand quietly in the distance.
Every journey begins with a single step.
Every dream begins with a single thought.
"""

with open("/content/poetry_corpus.txt", "w") as f:
    f.write(poetry_text)

print("Poetry corpus created!")

Poetry corpus created!

In [17]:
import os

CORPUS_PATH = "/content/poetry_corpus.txt"

print(os.path.exists(CORPUS_PATH))

True

In [20]:
# ==========================================================
# Poetry Generation — Fine-tune GPT-2
# ==========================================================

!pip install -U -q datasets huggingface_hub fsspec transformers accelerate

import os
import math
import torch

from datasets import load_dataset
from transformers import (
    GPT2Tokenizer,
    GPT2LMHeadModel,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)

# ==========================================================
# 1. Check GPU
# ==========================================================

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# ==========================================================
# 2. Set CORPUS PATH
# ==========================================================

CORPUS_PATH = "/content/poetry_corpus.txt"

# Check whether file exists
if not os.path.exists(CORPUS_PATH):
    raise FileNotFoundError(
        f"Poetry file not found at: {CORPUS_PATH}"
    )

print("Corpus found:", CORPUS_PATH)

# ==========================================================
# 3. Load poetry dataset
# ==========================================================

raw_dataset = load_dataset(
    "text",
    data_files={"train": CORPUS_PATH}
)

print(raw_dataset)

# Use a train/test split
split_datasets = raw_dataset["train"].train_test_split(
    test_size=0.2,
    seed=42
)

print(split_datasets)

# ==========================================================
# 4. Load GPT-2 tokenizer
# ==========================================================

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

# GPT-2 does not have a default padding token
# So we use EOS token as padding token
tokenizer.pad_token = tokenizer.eos_token

# Smaller block size because our dataset is small
BLOCK_SIZE = 32

# ==========================================================
# 5. Tokenization
# ==========================================================

def tokenize_function(examples):

    texts = [
        text + tokenizer.eos_token
        for text in examples["text"]
    ]

    return tokenizer(
        texts,
        truncation=False
    )


tokenized_datasets = split_datasets.map(
    tokenize_function,
    batched=True,
    remove_columns=["text"]
)

# ==========================================================
# 6. Group tokens into blocks
# ==========================================================

def group_texts(examples):

    # Combine all tokenized examples
    concatenated = sum(examples["input_ids"], [])

    # Keep only complete blocks
    total_length = (
        len(concatenated) // BLOCK_SIZE
    ) * BLOCK_SIZE

    input_ids = [
        concatenated[i:i + BLOCK_SIZE]
        for i in range(
            0,
            total_length,
            BLOCK_SIZE
        )
    ]

    return {
        "input_ids": input_ids,
        "labels": [ids.copy() for ids in input_ids]
    }


lm_datasets = tokenized_datasets.map(
    group_texts,
    batched=True,
    remove_columns=tokenized_datasets["train"].column_names,
)

lm_datasets.set_format("torch")

print("Training examples:", len(lm_datasets["train"]))
print("Testing examples:", len(lm_datasets["test"]))

# ==========================================================
# 7. Data Collator
# ==========================================================

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

# ==========================================================
# 8. Load GPT-2
# ==========================================================

model = GPT2LMHeadModel.from_pretrained("gpt2")

model.to(device)

# ==========================================================
# 9. Training arguments
# ==========================================================

training_args = TrainingArguments(
    output_dir="/content/gpt2-poetry-generator",

    # Number of epochs
    num_train_epochs=3,

    # Small dataset → small batch size
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,

    learning_rate=5e-5,

    weight_decay=0.01,

    logging_steps=1,

    eval_strategy="epoch",
    save_strategy="epoch",

    fp16=torch.cuda.is_available(),

    report_to="none"
)

# ==========================================================
# 10. Create Trainer
# ==========================================================

trainer = Trainer(
    model=model,
    args=training_args,

    train_dataset=lm_datasets["train"],
    eval_dataset=lm_datasets["test"],

    processing_class=tokenizer,

    data_collator=data_collator,
)

# ==========================================================
# 11. Fine-tune GPT-2
# ==========================================================

print("\nStarting GPT-2 fine-tuning...\n")

trainer.train()

print("\nTraining completed!")


# ==========================================================
# Evaluation
# ==========================================================

eval_results = trainer.evaluate()

print("\nEvaluation results:")
print(eval_results)

if "eval_loss" in eval_results:
    eval_loss = eval_results["eval_loss"]

    try:
        perplexity = math.exp(eval_loss)
    except OverflowError:
        perplexity = float("inf")

    print("Eval Loss:", eval_loss)
    print("Perplexity:", perplexity)
else:
    print("Evaluation loss is not available.")
    print("This can happen because the current poetry dataset is very small.")

# ==========================================================
# 13. Save model
# ==========================================================

FINAL_PATH = "/content/gpt2-poetry-generator/final"

trainer.save_model(FINAL_PATH)
tokenizer.save_pretrained(FINAL_PATH)

print("\nModel saved at:")
print(FINAL_PATH)

# ==========================================================
# 14. Generate poetry
# ==========================================================

def generate_poem(
    prompt,
    max_new_tokens=50,
    temperature=0.8,
    top_p=0.92,
    top_k=50
):

    model.eval()

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():

        outputs = model.generate(
            **inputs,

            max_new_tokens=max_new_tokens,

            do_sample=True,

            temperature=temperature,

            top_p=top_p,

            top_k=top_k,

            pad_token_id=tokenizer.eos_token_id,

            eos_token_id=tokenizer.eos_token_id
        )

    return tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )


# ==========================================================
# 15. Test prompts
# ==========================================================

prompts = [
    "The moon",
    "The morning sun",
    "The river"
]

print("\n==============================")
print("GENERATED POETRY")
print("==============================")

for prompt in prompts:

    result = generate_poem(
        prompt,
        max_new_tokens=50,
        temperature=0.8,
        top_p=0.92,
        top_k=50
    )

    print("\nPrompt:", prompt)
    print(result)
    print("-" * 50)

Using device: cuda
Corpus found: /content/poetry_corpus.txt
DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 15
    })
})
DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 12
    })
    test: Dataset({
        features: ['text'],
        num_rows: 3
    })
})
Training examples: 2
Testing examples: 0

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.

Starting GPT-2 fine-tuning...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

Evaluation results:
{}
Evaluation loss is not available.
This can happen because the current poetry dataset is very small.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model saved at:
/content/gpt2-poetry-generator/final

==============================
GENERATED POETRY
==============================

Prompt: The moon
The moon will be very bright and warm to the touch, and we will have a lot of energy to build up.

The sun will be very bright and warm to the touch, and we will have a lot of energy to build up. We will
--------------------------------------------------

Prompt: The morning sun
The morning sun was shining.

"It's just that I'm not sure how to describe it," said the man who, like his father, was a student in the University of Virginia, who said he was born in the South. "I think it
--------------------------------------------------

Prompt: The river
The river's water supply is so polluted, so polluted that it's like a virus," said Paul Smith, a hydrologist with the U.S. Geological Survey. "And that's why it's so important to understand the river's health, because
--------------------------------------------------