# Introduction to RAG

#ðŸ” How to Get Your Gemini API Key
To use the Gemini 1.5 Flash model in this notebook, youâ€™ll need a free API key from Google AI Studio. Follow the steps below to generate one:

Step-by-Step Instructions:

1. Visit Google AI Studio

  Open this link in your browser: https://aistudio.google.com/app/apikey

2. Sign in with Your Google Account

  Make sure you're signed in with a Google account (Gmail, Workspace, etc.).

3. Agree to Terms

  If it's your first time using AI Studio, you'll be asked to accept the terms and conditions.

4. Generate an API Key

  Click the â€œCreate API Keyâ€ button.

5. A key will be displayed. It will look something like this:
AI...123xyz

6. Copy Your API Key

  Make sure to copy and store it somewhere safe.

7. Youâ€™ll paste this key into the notebook cell below.

In [ ]:
import os

try:
    from google.colab import userdata
except ImportError:
    GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
else:
    GEMINI_API_KEY = userdata.get("GEMINI_API_Key")

if not GEMINI_API_KEY:
    raise RuntimeError(
        "Set the GEMINI_API_Key Colab Secret or the GEMINI_API_KEY environment variable."
    )

In [ ]:
import google.generativeai as genai
import os
import time
import datetime

genai.configure(api_key=GEMINI_API_KEY)

In [ ]:
model = genai.GenerativeModel("gemini-3.1-flash-lite")

In [ ]:
prompt = "Summarize the concept of reinforcement learning in AI."

In [ ]:
response = model.generate_content(prompt)
print(response.text)

At its simplest, **Reinforcement Learning (RL)** is a branch of machine learning where an AI agent learns to make decisions by performing actions in an environment and receiving feedback.

It is often described as **learning through trial and error**, modeled after the way humans and animals learn through rewards and punishments.

---

### The Core Components
To understand RL, imagine training a dog to sit. The process involves four key elements:

1.  **The Agent:** The AI learner or decision-maker (e.g., a robot, a game character).
2.  **The Environment:** The world the agent interacts with (e.g., a chessboard, a video game level, a stock market).
3.  **The Action:** What the agent does (e.g., move left, jump, buy a stock).
4.  **The Reward:** The feedback the agent receives after an action (e.g., +10 points for winning, -1 for hitting an obstacle, 0 for neutral moves).

### How It Works: The Feedback Loop
Reinforcement learning operates in a continuous loop:
*   **Observation:** The agent observes the current state of the environment.
*   **Action:** The agent chooses an action based on its current strategy (called a **Policy**).
*   **Reward:** The environment provides a reward or penalty based on that action.
*   **Learning:** The agent updates its policy to maximize the total reward over time.

### The "Exploration vs. Exploitation" Dilemma
A central challenge in RL is balancing two competing goals:
*   **Exploration:** The agent tries new, unfamiliar actions to see if they yield better rewards than its current strategy.
*   **Exploitation:** The agent relies on its current knowledge to choose the action that has yielded the best rewards in the past.

If an agent only exploits, it might get stuck in a "good enough" strategy without ever finding the "best" one. If it only explores, it will never actually use what it has learned.

### Why is it different from other AI?
*   **Supervised Learning:** The AI is given a dataset with the "correct answers" labeled (like showing a computer 1,000 photos of cats and telling it "this is a cat").
*   **Reinforcement Learning:** There is no "answer key." The AI has to figure out the best sequence of moves on its own, often over thousands or millions of attempts. It learns *how* to achieve a goal rather than just categorizing data.

### Real-World Applications
*   **Gaming:** RL agents have famously beaten human world champions in complex games like *Go* (AlphaGo), *StarCraft*, and *Dota 2*.
*   **Robotics:** Teaching robots how to walk, grasp objects, or navigate obstacles by letting them "practice" in simulations.
*   **Finance:** Algorithms that learn to optimize stock portfolios by reacting to market changes.
*   **Autonomous Vehicles:** Learning how to navigate traffic, change lanes, and prioritize safety based on rewards for efficiency and penalties for collisions.
*   **Recommendation Systems:** Fine-tuning the content displayed to users based on long-term engagement rather than just immediate clicks.

### Summary
Reinforcement learning is essentially **goal-oriented learning.** It is the most powerful method currently available for solving complex, sequential decision-making problems where the "right way" to act isn't known in advance, but the "desired outcome" is clear.



Your task is to use the optimal vector store you created in the last lab to build RAG App on the Book Crime and Punishment.
You may run this on local .py files instead of Colab or Jupyter notebooks for your ease. Use Gemini as your LLM.

## Step 1:
- Implement a chat app, where single turn conversations take place. i.e. question asked is answered directly, history is not maintained. Use streamlit for a clean interface.

## Step 2:
- Add history into conversation by saving conversation in variables. History will be saved in memory here, not stored. Your app should now be able to answer questions in multi-turn conversations within single session.

## Step 3:
- Use supabase or any other database to store chats. This will be a relational database, with a Chat table, containing Roles:(varchar: 'ai', 'user'), Message (varchar). Your app should now be able to answer questions in multi-turn conversations even if session restarts.

<br> <br>

## Resources:
- Streamlit: https://docs.streamlit.io/develop/tutorials/chat-and-llm-apps/build-conversational-apps
- Langchain: https://medium.com/data-science/retrieval-augmented-generation-rag-from-theory-to-langchain-implementation-4e9bd5f6a4f2
<br> <br>
Feel free to search for additional resources

## Step 4
Evaluate your RAG App using ragas:

- https://docs.ragas.io/en/stable/getstarted/evals/
- https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/
- https://docs.ragas.io/en/stable/howtos/applications/

# **Step 1**

In [ ]:
import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

Gemini key loaded: True

In [6]:
!pip install -q -U \
    langchain \
    langchain-community \
    langchain-chroma \
    langchain-google-genai \
    langchain-huggingface \
    chromadb \
    sentence-transformers \
    pypdf \
    streamlit \
    pyngrok \
    supabase \
    ragas

   â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 147.8/147.8 kB 9.2 MB/s eta 0:00:00
   â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 74.2/74.2 kB 5.3 MB/s eta 0:00:00
   â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 739.6/739.6 kB 33.7 MB/s eta 0:00:00

In [8]:
from google.colab import files

uploaded = files.upload()

Saving crime-and-punishment.pdf to crime-and-punishment.pdf

In [9]:
from langchain_community.document_loaders import PyPDFLoader

PDF_PATH = "/content/crime-and-punishment.pdf"

loader = PyPDFLoader(PDF_PATH)

documents = loader.load()

print("Number of pages:", len(documents))

Number of pages: 767

In [11]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)

chunks = text_splitter.split_documents(documents)

print("Number of chunks:", len(chunks))

Number of chunks: 3042

In [13]:
from langchain_huggingface import HuggingFaceEmbeddings

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [14]:
from langchain_chroma import Chroma

vectorstore = Chroma.from_documents(
    documents=chunks,
    embedding=embedding_model,
    collection_name="crime_and_punishment"
)

print("Vector store created successfully.")

Vector store created successfully.

In [15]:
retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 5}
)

query = "Who is Sonia and what is her relationship with Raskolnikov?"

results = retriever.invoke(query)

for i, doc in enumerate(results, 1):
    print("=" * 80)
    print(f"RESULT {i}")
    print("=" * 80)
    print(doc.page_content[:1500])

================================================================================
RESULT 1
================================================================================
her before and he had only roused it again.
â€˜And, what, if even now, while Katerina Ivanovna is alive,
you get ill and are taken to the hospital, what will happen
then?â€™ he persisted pitilessly.
â€˜How can you? That cannot be!â€™
And Soniaâ€™s face worked with awful terror.
â€˜Cannot be?â€™ Raskolnikov went on with a harsh smile.
â€˜You are not insured against it, are you? What will happen
to them then? They will be in the street, all of them, she will
================================================================================
RESULT 2
================================================================================
â€˜Well, after that I can understand your living like this,â€™
Raskolnikov said with a bitter smile.
â€˜And arenâ€™t you sorry for them? Arenâ€™t you sorry?â€™ Sonia
flew at him again. â€˜Why, I know, you gave your last penny
yourself, though youâ€™d seen nothing of it, and if youâ€™d seen
everything, oh dear! And how often, how often Iâ€™ve brought
her to tears! Only last week! Yes, I! Only a week before his
death. I was cruel! And how often Iâ€™ve done it! Ah, Iâ€™ve been
================================================================================
RESULT 3
================================================================================
â€¦â€™ she forced herself at last to read, but at the third word her
voice broke like an overstrained string. There was a catch
in her breath.
Raskolnikov saw in part why Sonia could not bring
herself to read to him and the more he saw this, the more
roughly and irritably he insisted on her doing so. He un -
derstood only too well how painful it was for her to betray
and unveil all that was her own. He understood that these
feelings really were her secret treasure  which she had kept
================================================================================
RESULT 4
================================================================================
1Free eBooks at Planet eBook.com
Sonia heard Raskolnikovâ€™s request distrustfully and
moved hesitatingly to the table. She took the book however.
â€˜Havenâ€™t you read it?â€™ she asked, looking up at him across
the table.
Her voice became sterner and sterner.
â€˜Long agoâ€¦. When I was at school. Read!â€™
â€˜And havenâ€™t you heard it in church?â€™
â€˜I â€¦ havenâ€™t been. Do you often go?â€™
â€˜N-no,â€™ whispered Sonia.
Raskolnikov smiled.
â€˜I understandâ€¦. And you wonâ€™t go to your fatherâ€™s fu -
neral to-morrow?â€™
================================================================================
RESULT 5
================================================================================
picture of their unfortunate brotherâ€™s life. Soniaâ€™s letters
were full of the most matter-of-fact detail, the simplest and
clearest description of all Raskolnikovâ€™s surroundings as a
convict. There was no word of her own hopes, no conjec -
ture as to the future, no description of her feelings. Instead
of any attempt to interpret his state of mind and inner life,
she gave the simple factsâ€”that is, his own words, an exact
account of his health, what he asked for at their interviews,

In [ ]:
import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

In [ ]:
llm = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite",
    temperature=0.2,
    google_api_key=os.environ["GOOGLE_API_KEY"]
)

In [28]:
from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_template("""
You are an AI assistant answering questions about Fyodor Dostoevsky's
Crime and Punishment.

Answer the user's question using ONLY the provided context.

If the answer cannot be found in the context, say:
"I could not find enough information in the book to answer this question."

Do not invent facts.

Context:
{context}

Question:
{question}

Answer:
""")

In [29]:
def rag_answer(question):

    docs = retriever.invoke(question)

    context = "\n\n".join(
        [doc.page_content for doc in docs]
    )

    formatted_prompt = prompt.invoke({
        "context": context,
        "question": question
    })

    response = llm.invoke(formatted_prompt)

    return response.content

In [30]:
answer = rag_answer(
    "Who is Razumikhin?"
)

print(answer)

[{'type': 'text', 'text': "Razumikhin was one of Raskolnikov's old comrades at the university.", 'extras': {'signature': 'EnEKbwERTTIPoPYTm5t85CuIyn5ODO8uJCEWHMHCV7gRmTgzoYLy9+KFoY1alzUmuMj2uTHrn5/bH7uI7E65XANm5/lk0M4QHVwzNdLJBbwR8pzTo/kdy2bU30v3B5rZ8BAXJS1O2FVW2YUwqlBnzVpYaQ=='}}]

In [ ]:
%%writefile app.py

import os
import streamlit as st

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate

# CONFIGURATION

PDF_PATH = "/content/crime-and-punishment.pdf"

GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")

# PAGE CONFIG
st.set_page_config(
    page_title="Crime and Punishment RAG",
    page_icon="ðŸ“š",
    layout="centered"
)

st.title("Crime and Punishment â€” RAG Assistant")

st.caption(
    "Ask questions about Dostoevsky's Crime and Punishment."
)

# CHECK API KEY
if not GOOGLE_API_KEY:

    st.error(
        "GOOGLE_API_KEY is not configured."
    )

    st.stop()
# CHECK PDF

if not os.path.exists(PDF_PATH):

    st.error(
        f"Book PDF not found at: {PDF_PATH}"
    )

    st.stop()

# LOAD PDF + CREATE VECTOR STORE

@st.cache_resource
def create_vectorstore():

    st.info("Loading Crime and Punishment and creating embeddings...")

    # Load PDF
    loader = PyPDFLoader(PDF_PATH)

    documents = loader.load()

    # Split into chunks
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=100
    )

    chunks = splitter.split_documents(documents)

    # Embedding model
    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

    # Create Chroma vector store
    vectorstore = Chroma.from_documents(
        documents=chunks,
        embedding=embeddings,
        collection_name="crime_and_punishment"
    )

    return vectorstore


vectorstore = create_vectorstore()

# RETRIEVER
retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 5
    }
)
# GEMINI
llm = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite",
    temperature=0.2,
    google_api_key=GOOGLE_API_KEY
)

# RAG PROMPT
prompt = ChatPromptTemplate.from_template("""

You are a helpful RAG assistant for Fyodor Dostoevsky's
Crime and Punishment.

Answer the user's question using ONLY the retrieved context
from the book.

Rules:

1. Do not invent information.
2. Do not use information that is not supported by the context.
3. If the answer cannot be found in the retrieved context,
   say:

"I could not find enough information in the retrieved text
to answer this question."

4. Give a clear and concise answer.
5. Do not mention that you are an AI.
6. Do not mention the retrieval process unless asked.

Retrieved Context:
------------------
{context}
------------------

Question:
{question}

Answer:
""")

# EXTRACT TEXT FROM GEMINI RESPONSE
def extract_response_text(response):

    # LangChain AIMessage normally stores the answer in .content
    if hasattr(response, "content"):

        content = response.content

    else:

        content = response

    # Normal string response
    if isinstance(content, str):

        return content

    # Structured Gemini response

    if isinstance(content, list):

        text_parts = []

        for item in content:

            if isinstance(item, dict):

                if item.get("type") == "text":

                    text = item.get("text", "")

                    if text:

                        text_parts.append(text)

        if text_parts:

            return "\n".join(text_parts)

    # Fallback

        return str(content)

# RAG FUNCTION
def answer_question(question):

    # 1. Retrieve relevant documents
    docs = retriever.invoke(question)

    # 2. Build context
    context = "\n\n".join(
        doc.page_content
        for doc in docs
    )

    # 3. Create prompt
    messages = prompt.invoke({
        "context": context,
        "question": question
    })

    # 4. Ask Gemini
    response = llm.invoke(messages)

    # 5. Extract clean answer
    answer = extract_response_text(response)

    return answer, docs

# STREAMLIT UI
question = st.text_area(
    "Ask a question",
    placeholder="Example: Who is Sonia?",
    height=100
)

# ASK BUTTON
if st.button("Ask", type="primary"):

    if not question.strip():

        st.warning(
            "Please enter a question first."
        )

    else:

        with st.spinner(
            "Searching Crime and Punishment..."
        ):

            answer, retrieved_docs = answer_question(
                question
            )

        # Display answer
        st.subheader("Answer")

        st.write(answer)

        # Display retrieved sources
        with st.expander(
            "View Retrieved Context"
        ):

            for i, doc in enumerate(
                retrieved_docs,
                start=1
            ):

                st.markdown(
                    f"**Retrieved Passage {i}**"
                )

                st.write(
                    doc.page_content
                )

                # Page metadata
                if "page" in doc.metadata:

                    st.caption(
                        f"PDF Page: {doc.metadata['page'] + 1}"
                    )

                st.divider()

Overwriting app.py

In [69]:
!streamlit run app.py &>/content/streamlit.log &

In [70]:
!pip install -q pyngrok

In [71]:
from pyngrok import ngrok

ngrok.kill()

print("All ngrok tunnels stopped.")

All ngrok tunnels stopped.

In [72]:
import time
time.sleep(3)

In [73]:
from pyngrok import ngrok

public_url = ngrok.connect(8501)

print("Streamlit URL:")
print(public_url)

Streamlit URL:
NgrokTunnel: "https://docile-matchless-grinch.ngrok-free.dev" -> "http://localhost:8501"

# **Step 2**

In [76]:
import os
import streamlit as st

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate

# CONFIGURATION
PDF_PATH = "/content/crime-and-punishment.pdf"

# Make sure this environment variable exists in Colab
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEYS")

# PAGE CONFIG
st.set_page_config(
    page_title="Crime and Punishment RAG",
    page_icon="ðŸ“š",
    layout="centered"
)

st.title("Crime and Punishment â€” RAG Assistant")

st.caption(
    "Multi-turn RAG assistant with conversation memory."
)

# CHECK API KEY
if not GOOGLE_API_KEY:
    st.error(
        "GOOGLE_API_KEY is not configured. "
        "Please add your Gemini API key before running the app."
    )
    st.stop()

# STEP 2: INITIALIZE CHAT HISTORY
# This history exists only while the current Streamlit
# session is active. It is NOT stored in a database.

if "messages" not in st.session_state:
    st.session_state.messages = []

# LOAD PDF + CREATE VECTOR STORE
@st.cache_resource
def create_vectorstore():

    loader = PyPDFLoader(PDF_PATH)

    documents = loader.load()

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=100
    )

    chunks = splitter.split_documents(documents)

    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

    vectorstore = Chroma.from_documents(
        documents=chunks,
        embedding=embeddings,
        collection_name="crime_and_punishment"
    )

    return vectorstore


with st.spinner("Loading Crime and Punishment..."):
    vectorstore = create_vectorstore()

# RETRIEVER
retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 5}
)

# GEMINI
llm = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite",
    temperature=0.2,
    google_api_key=GOOGLE_API_KEY
)

# DISPLAY PREVIOUS CONVERSATION
for message in st.session_state.messages:

    with st.chat_message(message["role"]):
        st.markdown(message["content"])


# RAG + CONVERSATION FUNCTION
def answer_question(question):

    # Retrieve relevant book content
    docs = retriever.invoke(question)

    context = "\n\n".join(
        doc.page_content
        for doc in docs
    )

    # Convert previous conversation into text
    conversation_history = ""

    for message in st.session_state.messages:

        role = message["role"].upper()

        conversation_history += (
            f"{role}: {message['content']}\n"
        )

   # Prompt
    prompt = ChatPromptTemplate.from_template(
        """
You are a helpful RAG assistant for
Crime and Punishment by Fyodor Dostoevsky.

Your job is to answer questions using the provided
book context.

IMPORTANT RULES:

1. Use the retrieved book context as the primary source.
2. Use conversation history to understand references
   such as "he", "she", "that character", "what happened next",
   or follow-up questions.
3. Do not invent information.
4. If the answer cannot be supported by the retrieved
   context, say:

"I could not find enough information in the book to answer this question."

5. Keep the answer clear and concise.

CONVERSATION HISTORY:
{history}

RETRIEVED BOOK CONTEXT:
{context}

CURRENT QUESTION:
{question}

ANSWER:
"""
    )

    messages = prompt.invoke({
        "history": conversation_history,
        "context": context,
        "question": question
    })

    response = llm.invoke(messages)

    return response.content

# CHAT INPUT
question = st.chat_input(
    "Ask something about Crime and Punishment..."
)

# PROCESS USER QUESTION
if question:

    # Display user message
    with st.chat_message("user"):
        st.markdown(question)

    # Save user message in session memory
    st.session_state.messages.append({
        "role": "user",
        "content": question
    })

    # Generate answer
    with st.chat_message("assistant"):

        with st.spinner("Searching the book..."):

            answer = answer_question(question)

        st.markdown(answer)

    # Save AI response in session memory
    st.session_state.messages.append({
        "role": "assistant",
        "content": answer
    })

# SIDEBAR
with st.sidebar:

    st.header("Conversation")

    st.write(
        f"Messages in memory: "
        f"{len(st.session_state.messages)}"
    )

    if st.button("Clear Conversation"):

        st.session_state.messages = []

        st.rerun()

2026-08-22 19:46:56.451 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:56.454 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:56.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:56.463 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:56.467 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:56.470 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:56.472 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:56.474 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:56.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.232 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.234 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.234 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.235 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.237 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.237 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.239 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.240 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.241 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.242 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.242 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.244 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.244 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.245 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.246 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.248 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.248 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-22 19:46:57.249 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

# **Step 3**

In [78]:
!pip install -q -U \
    streamlit \
    langchain-community \
    langchain-text-splitters \
    langchain-huggingface \
    langchain-chroma \
    langchain-google-genai \
    chromadb \
    sentence-transformers \
    pypdf \
    supabase \
    pyngrok

In [82]:
import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")
os.environ["SUPABASE_URL"] = userdata.get("SUPABASE_URL")
os.environ["SUPABASE_KEY"] = userdata.get("SUPABASE_KEY")

print("GOOGLE_API_KEY:", bool(os.environ["GOOGLE_API_KEY"]))
print("SUPABASE_URL:", bool(os.environ["SUPABASE_URL"]))
print("SUPABASE_KEY:", bool(os.environ["SUPABASE_KEY"]))

GOOGLE_API_KEY: True
SUPABASE_URL: True
SUPABASE_KEY: True

In [91]:
app_code = r'''
import os
import streamlit as st

from supabase import create_client

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate

# CONFIGURATION
PDF_PATH = "/content/crime-and-punishment.pdf"

COLLECTION_NAME = "crime_and_punishment_step3"

CHROMA_PATH = "/content/chroma_db"


# LOAD ENVIRONMENT VARIABLES
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")
SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")


if not GOOGLE_API_KEY:
    st.error("GOOGLE_API_KEY is missing.")
    st.stop()

if not SUPABASE_URL:
    st.error("SUPABASE_URL is missing.")
    st.stop()

if not SUPABASE_KEY:
    st.error("SUPABASE_KEY is missing.")
    st.stop()

# STREAMLIT PAGE
st.set_page_config(
    page_title="Crime and Punishment RAG",
    page_icon="ðŸ“š",
    layout="centered"
)

st.title("Crime and Punishment RAG Assistant")

st.caption(
    "Persistent multi-turn RAG chatbot using Gemini, "
    "Chroma and Supabase."
)

# CHECK PDF
if not os.path.exists(PDF_PATH):

    st.error(
        f"PDF not found at: {PDF_PATH}"
    )

    st.info(
        "Upload crime-and-punishment.pdf to /content "
        "before starting the Streamlit application."
    )

    st.stop()

# SUPABASE CLIENT
supabase = create_client(
    SUPABASE_URL,
    SUPABASE_KEY
)

# CREATE / LOAD VECTOR STORE
@st.cache_resource
def create_vectorstore():

    print("Loading Crime and Punishment...")

    loader = PyPDFLoader(PDF_PATH)

    documents = loader.load()

    print(f"Loaded {len(documents)} pages.")

    # Chunking
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=100
    )

    chunks = splitter.split_documents(documents)

    print(f"Created {len(chunks)} chunks.")

    # Embeddings
    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )
    # Chroma
    vectorstore = Chroma(
        collection_name=COLLECTION_NAME,
        embedding_function=embeddings,
        persist_directory=CHROMA_PATH
    )

    # Check if collection is empty
    try:
        collection_count = vectorstore._collection.count()
    except Exception:
        collection_count = 0

    # Only add documents if Chroma is empty
    if collection_count == 0:

        print("Chroma collection is empty.")
        print("Adding documents...")

        vectorstore.add_documents(chunks)

        print("Documents added to Chroma.")

    else:

        print(
            f"Existing Chroma collection found "
            f"with {collection_count} documents."
        )

    return vectorstore


with st.spinner(
    "Loading Crime and Punishment vector store..."
):

    vectorstore = create_vectorstore()

# RETRIEVER
retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 5
    }
)

# GEMINI
llm = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite",
    temperature=0.2,
    api_key=GOOGLE_API_KEY
)

# DATABASE FUNCTIONS
def get_messages():

    try:

        result = (
            supabase
            .table("chats")
            .select(
                "id,role,message,created_at"
            )
            .order(
                "created_at",
                desc=False
            )
            .execute()
        )

        return result.data

    except Exception as e:

        st.error(
            f"Could not load chat history: {e}"
        )

        return []


def save_message(role, message):

    try:

        supabase.table("chats").insert({
            "role": role,
            "message": message
        }).execute()

    except Exception as e:

        st.error(
            f"Could not save message: {e}"
        )


def clear_messages():

    try:

        supabase \
            .table("chats") \
            .delete() \
            .gt("id", 0) \
            .execute()

        return True

    except Exception as e:

        st.error(
            f"Could not clear chat history: {e}"
        )

        return False

# LOAD PERSISTENT CHAT HISTORY
chat_history = get_messages()

# SIDEBAR
with st.sidebar:

    st.header("Chat Information")

    st.write(
        f"Messages stored in Supabase: "
        f"{len(chat_history)}"
    )

    st.divider()

    if st.button(
        "Clear Chat History",
        use_container_width=True
    ):

        if clear_messages():

            st.success(
                "Chat history cleared."
            )

            st.rerun()

# DISPLAY OLD CHAT HISTORY
for message in chat_history:

    role = message["role"]

    if role == "ai":
        display_role = "assistant"
    else:
        display_role = "user"

    with st.chat_message(display_role):

        st.markdown(
            message["message"]
        )

# RAG PROMPT
prompt = ChatPromptTemplate.from_template(
    """
You are a RAG assistant for the book
"Crime and Punishment" by Fyodor Dostoevsky.

Your job is to answer the user's question using
the retrieved context from the book and the previous
conversation.

IMPORTANT RULES:

1. Use the retrieved book context as the primary source.

2. Use conversation history to understand follow-up
questions.

3. Do not invent facts.

4. Do not claim information that is not supported
by the retrieved context.

5. If the book context does not contain enough
information to answer the question, say:

"I could not find enough information in the book
to answer this question."

6. Keep the answer clear and reasonably concise.

7. If the user asks a follow-up question such as
"What about her?", use the conversation history
to understand who "her" refers to.

------------------------------------------------------------
CONVERSATION HISTORY
------------------------------------------------------------

{history}

------------------------------------------------------------
RETRIEVED BOOK CONTEXT
------------------------------------------------------------

{context}

------------------------------------------------------------
CURRENT QUESTION
------------------------------------------------------------

{question}

------------------------------------------------------------
ANSWER
------------------------------------------------------------
"""
)

# RAG FUNCTION
def answer_question(question):

    # Retrieve relevant book chunks

    docs = retriever.invoke(question)

    # Build context
    context = "\n\n".join(
        doc.page_content
        for doc in docs
    )

    # Build conversation history
    history_text = ""

    for message in chat_history:

        role = message["role"]

        if role == "user":

            history_text += (
                f"USER: {message['message']}\n"
            )

        else:

            history_text += (
                f"AI: {message['message']}\n"
            )

    # Create prompt
   messages = prompt.invoke({
        "history": history_text,
        "context": context,
        "question": question
    })

    # Ask Gemini
   response = llm.invoke(messages)

    answer = response.content

    # Handle structured Gemini responses
    if isinstance(answer, list):

        text_parts = []

        for item in answer:

            if isinstance(item, dict):

                if item.get("type") == "text":

                    text_parts.append(
                        item.get("text", "")
                    )

            elif isinstance(item, str):

                text_parts.append(item)

        answer = "\n".join(text_parts)

    return str(answer)

# STREAMLIT CHAT INPUT
question = st.chat_input(
    "Ask a question about Crime and Punishment..."
)


# PROCESS NEW QUESTION
if question:

    # Show user message
    with st.chat_message("user"):

        st.markdown(question)

    # Save user message

    save_message(
        "user",
        question
    )

    # Generate AI response
    with st.chat_message("assistant"):

        with st.spinner(
            "Searching the book and generating an answer..."
        ):

            answer = answer_question(question)

        st.markdown(answer)

    # Save AI response

    save_message(
        "ai",
        answer
    )

    # Refresh Streamlit

    st.rerun()

# FOOTER
st.divider()

st.caption(
    "Conversation history is persisted in Supabase. "
    "Book knowledge is retrieved from the Chroma vector store."
)
'''

with open("/content/app.py", "w", encoding="utf-8") as f:
    f.write(app_code)

print("âœ… app.py created successfully!")

âœ… app.py created successfully!

In [92]:
!pkill -f streamlit || true
!streamlit run /content/app.py > /content/streamlit.log 2>&1 &

^C

In [93]:
import time

time.sleep(5)

print("Streamlit started.")

WARNING:pyngrok.process.ngrok:t=2026-08-22T21:07:20+0000 lvl=warn msg="failed to open private leg" id=fe23f9dd140a privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-22T21:07:20+0000 lvl=warn msg="failed to open private leg" id=e5c23a13b01b privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-22T21:07:21+0000 lvl=warn msg="failed to open private leg" id=5dba2acebcb1 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-22T21:07:21+0000 lvl=warn msg="failed to open private leg" id=7733206c9eeb privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-22T21:07:23+0000 lvl=warn msg="failed to open private leg" id=907ed87b0adb privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-22T21:07:23+0000 lvl=warn msg="failed to open private leg" id=d72c10b2fc6e privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"

Streamlit started.

In [94]:
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-08-22 21:07:25.003 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://8.228.126.179:8501

In [95]:
from google.colab import userdata
from pyngrok import ngrok

NGROK_AUTH_TOKEN = userdata.get("NGROK_AUTH_TOKEN")

ngrok.set_auth_token(NGROK_AUTH_TOKEN)

ngrok.kill()

public_url = ngrok.connect(8501)

print("Your Streamlit URL:")
print(public_url)

Your Streamlit URL:
NgrokTunnel: "https://docile-matchless-grinch.ngrok-free.dev" -> "http://localhost:8501"

# **Step 4**

In [117]:
# Evaluate Crime and Punishment RAG using RAGAS

# 1. INSTALL RAGAS

!pip install -q -U ragas

# 2. IMPORTS
import pandas as pd
from ragas import EvaluationDataset, evaluate
from ragas.llms import LangchainLLMWrapper

from ragas.metrics import (
    LLMContextRecall,
    Faithfulness,
    FactualCorrectness
)

# 3. CREATE TEST QUESTIONS
# IMPORTANT:
# For Context Recall and Factual Correctness, we need
# reference/ground-truth answers.
# These answers should be based on Crime and Punishment.

test_data = [

    {
        "user_input": "Who is Raskolnikov?",
        "reference":
            "Rodion Raskolnikov is the central character of "
            "Crime and Punishment. He is a former student who "
            "commits a murder and struggles with guilt, "
            "morality, and the consequences of his actions."
    },

    {
        "user_input": "Who is Sonia Marmeladova?",
        "reference":
            "Sonia Marmeladova is the daughter of Marmeladov. "
            "She is forced into prostitution to support her family "
            "and becomes an important source of compassion and "
            "moral support for Raskolnikov."
    },

    {
        "user_input": "Why did Raskolnikov kill the old woman?",
        "reference":
            "Raskolnikov kills Alyona Ivanovna because he believes "
            "that extraordinary people may be justified in "
            "transgressing moral laws for a supposedly greater "
            "purpose. His theory is connected to his desire to "
            "test whether he himself is such a person."
    },

    {
        "user_input": "Who is Porfiry Petrovich?",
        "reference":
            "Porfiry Petrovich is the investigating magistrate "
            "who investigates the murder of Alyona Ivanovna. "
            "He becomes increasingly suspicious of Raskolnikov "
            "and uses psychological pressure to expose the truth."
    },

    {
        "user_input": "What happens to Raskolnikov at the end of the novel?",
        "reference":
            "Raskolnikov confesses to his crime and is sent to "
            "Siberia for punishment. Sonia follows him and remains "
            "supportive. His imprisonment begins a process of "
            "moral and spiritual transformation."
    },

    {
        "user_input": "What is the relationship between Sonia and Raskolnikov?",
        "reference":
            "Sonia becomes closely connected to Raskolnikov and "
            "provides him with compassion, emotional support, and "
            "moral guidance. Their relationship becomes important "
            "to Raskolnikov's spiritual transformation."
    },

    {
        "user_input": "Who is Svidrigailov?",
        "reference":
            "Arkady Svidrigailov is a wealthy and morally ambiguous "
            "character connected to Dunya and Raskolnikov. His "
            "actions and character provide a contrast to Raskolnikov "
            "and contribute to the novel's exploration of morality."
    },

    {
        "user_input": "What is Raskolnikov's theory about extraordinary people?",
        "reference":
            "Raskolnikov's theory suggests that extraordinary people "
            "may have the right to violate ordinary moral laws if "
            "their actions are directed toward a greater purpose."
    },

    {
        "user_input": "Who was Alyona Ivanovna?",
        "reference":
            "Alyona Ivanovna was an elderly pawnbroker whom "
            "Raskolnikov murders at the beginning of the novel."
    },

    {
        "user_input": "How does Sonia influence Raskolnikov?",
        "reference":
            "Sonia influences Raskolnikov through her compassion, "
            "faith, loyalty, and willingness to remain with him "
            "despite his crime. Her support contributes to his "
            "eventual moral and spiritual transformation."
    }
]


print("Number of test questions:", len(test_data))


# 4. RUN YOUR RAG SYSTEM ON EACH QUESTION
evaluation_rows = []


for i, item in enumerate(test_data):

    question = item["user_input"]
    reference = item["reference"]

    print("=" * 70)
    print(f"Question {i + 1}/{len(test_data)}")
    print(question)

    try:

        # Retrieve documents
        docs = retriever.invoke(question)

        retrieved_contexts = [
            doc.page_content
            for doc in docs
        ]
     # Generate answer using YOUR RAG application
        answer = answer_question(question)
    # Save evaluation sample
        evaluation_rows.append({

            "user_input": question,

            "retrieved_contexts":
                retrieved_contexts,

            "response":
                str(answer),

            "reference":
                reference
        })

        print("\nGenerated answer:")
        print(answer)

    except Exception as e:

        print("\nERROR:")
        print(e)

# 5. CHECK GENERATED DATASET
print("\n")
print("=" * 70)
print("RAG EVALUATION DATASET")
print("=" * 70)

print(
    "Successful samples:",
    len(evaluation_rows)
)

# 6. CONVERT TO RAGAS EvaluationDataset
evaluation_dataset = EvaluationDataset.from_list(
    evaluation_rows
)

print("\nRagas dataset created successfully.")

print(
    "Features:",
    evaluation_dataset.features()
)

# 7. CREATE EVALUATOR LLM
# We use Gemini to judge our RAG application's answers.
evaluator_llm = LangchainLLMWrapper(llm)

# 8. SELECT RAGAS METRICS
metrics = [

    # Checks whether retrieved context supports
    # the information required by the reference answer.
    LLMContextRecall(
        llm=evaluator_llm
    ),

    # Checks whether the generated answer is
    # supported by the retrieved context.
    Faithfulness(
        llm=evaluator_llm
    ),

    # Checks factual correctness against
    # the reference answer.
    FactualCorrectness(
        llm=evaluator_llm
    )
]

# 9. RUN EVALUATION
print("\n")
print("=" * 70)
print("STARTING RAGAS EVALUATION")
print("=" * 70)

results = evaluate(

    dataset=evaluation_dataset,

    metrics=metrics,

    llm=evaluator_llm
)

# 10. DISPLAY RESULTS
print("\n")
print("=" * 70)
print("RAGAS RESULTS")
print("=" * 70)

print(results)


# 11. CONVERT RESULTS TO DATAFRAME
results_df = results.to_pandas()

print("\n")
print("=" * 70)
print("PER-QUESTION RESULTS")
print("=" * 70)

display(results_df)

# 12. CALCULATE AVERAGE SCORES
score_columns = [
    column
    for column in [
        "context_recall",
        "faithfulness",
        "factual_correctness"
    ]
    if column in results_df.columns
]


print("\n")
print("=" * 70)
print("AVERAGE SCORES")
print("=" * 70)

average_scores = results_df[score_columns].mean()

display(
    average_scores.to_frame(
        name="Average Score"
    )
)

# 13. INTERPRET THE RESULTS
print("\n")
print("=" * 70)
print("INTERPRETATION")
print("=" * 70)

for metric_name, score in average_scores.items():

    print(
        f"{metric_name}: {score:.3f}"
    )

    if score >= 0.90:

        print(
            "  Excellent performance."
        )

    elif score >= 0.75:

        print(
            "  Good performance, but there is room for improvement."
        )

    elif score >= 0.60:

        print(
            "  Moderate performance. Retrieval or generation "
            "should be improved."
        )

    else:

        print(
            "  Poor performance. Investigate retrieval, "
            "chunking, prompts, or the LLM."
        )

# 14. SAVE RESULTS
results_df.to_csv(
    "/content/ragas_results.csv",
    index=False
)

print(
    "\nResults saved to:"
    "/content/ragas_results.csv"
)

# 15. SAVE TEST DATASET
pd.DataFrame(
    test_data
).to_json(
    "/content/ragas_test_dataset.json",
    orient="records",
    indent=2
)

print(
    "Test dataset saved to:"
    "/content/ragas_test_dataset.json"
)


# 16. FINAL SUMMARY
print("\n")
print("=" * 70)
print("STEP 4 COMPLETED")
print("=" * 70)

print("""
Your Crime and Punishment RAG application has now been
evaluated using Ragas.

Metrics evaluated:

1. Context Recall
   -> Did retrieval find the information needed?

2. Faithfulness
   -> Is the generated answer supported by the retrieved
      book context?

3. Factual Correctness
   -> Is the generated answer factually consistent with
      the expected/reference answer?

Use the scores to decide what to improve next:
- chunk size
- chunk overlap
- number of retrieved documents (k)
- embedding model
- prompt
- Gemini temperature
- retrieval strategy
""")

2026-08-22 22:10:23.022 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Number of test questions: 10
======================================================================
Question 1/10
Who is Raskolnikov?

2026-08-22 22:10:26.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Generated answer:
[{'type': 'text', 'text': 'I could not find enough information in the book to answer this question.', 'extras': {'signature': 'EnEKbwERTTIPXj/emxeflcye4vHrXo6Wb4SIi6KcgfDVqSoEM/LKo1J5U+jxizOX2eWM8fjSSWX9P7S5S3o2DlvojivpYr8YtaxSIkjns1Ve7ikPdXnigp3KDq3ptPNL1RqRcYWXt5k7VIFYhNMwTZkKhQ=='}}]
======================================================================
Question 2/10
Who is Sonia Marmeladova?

2026-08-22 22:10:31.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Generated answer:
[{'type': 'text', 'text': 'Sonia Marmeladova is described as the daughter of the sick man (Marmeladov) and is referred to as an "eternal victim." She is a character who faces a life of sacrifice and is described as living on the "edge of the abyss of loathsomeness."', 'extras': {'signature': 'EnEKbwERTTIP4n+jd3x8cbnzPOz0cJpx68VTpxkT0re4ts93Yc/bod22wznKlmuBEAqQMKu89t0Rw42MDZXEGUA1YX9GpwhfGcbTLDJLuUQxrYV6rrlPQLhKbZHDUDocjzgBMCsRAQtwzCufFJtlfX9QeA=='}}]
======================================================================
Question 3/10
Why did Raskolnikov kill the old woman?

2026-08-22 22:10:33.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Generated answer:
[{'type': 'text', 'text': 'I could not find enough information in the book to answer this question.', 'extras': {'signature': 'EnEKbwERTTIPHRN6BIhGwViNg9pAnfkb6XvGRiBTNrC+IE5PZc6wY4qYW3xgATpI9412/R7xMslO8uF8I+EMtHT/Dg5DfbTG+3qmRlrAqaKEYIHfjZuU/lrirIS/f/f4NqJpjEVjbz/xDNvGnUp39B0RVw=='}}]
======================================================================
Question 4/10
Who is Porfiry Petrovich?

2026-08-22 22:10:36.622 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Generated answer:
[{'type': 'text', 'text': 'Porfiry Petrovich is a man who holds an official position, as indicated by the fact that his study is furnished with "government furniture." He is involved in the investigation concerning Raskolnikov, as evidenced by Raskolnikov being summoned to him and their discussion regarding whether Raskolnikov is under suspicion. In his study, he is described as wearing a dressing-gown, clean linen, and trodden-down slippers.', 'extras': {'signature': 'EnEKbwERTTIPeInK1nlQsHqYhV3axmOs9xgVQLMdYiCYt0T8uUDlR+SpUfpFwdJP6y9bEGFuFQDa17LhYrKZXxGAxazSy8lS6tCZ8uVOZPE3OhjyLb0hhMJhKSisLbCF7P9JWTiB3NnaL5oU2AsVSGzcQw=='}}]
======================================================================
Question 5/10
What happens to Raskolnikov at the end of the novel?

2026-08-22 22:10:37.192 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Generated answer:
[{'type': 'text', 'text': 'I could not find enough information in the book to answer this question.', 'extras': {'signature': 'EnEKbwERTTIPBX+DItPiYT6skB7hZ+eZkfwFtOqUMHVYmAo+A99q1OSAQVG6kZhF8EXClH5FCnCrZugGNZnHSwZ8nWkgL+vPnV/q+kYgwgUN61dq4KoaIWD+j8tA1yvBXjTmcEXsB5k1wQKU5SiyyLRDtg=='}}]
======================================================================
Question 6/10
What is the relationship between Sonia and Raskolnikov?

2026-08-22 22:10:38.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Generated answer:
[{'type': 'text', 'text': 'Based on the provided text, the relationship between Sonia and Raskolnikov involves a dynamic where Raskolnikov challenges Sonia regarding her difficult life and the welfare of her family, often speaking to her "pitilessly." Conversely, Sonia shows deep concern for others, questioning Raskolnikov about his own capacity for pity.\n\nLater, during Raskolnikov\'s time as a convict, their relationship is characterized by Sonia\'s devoted support. She writes letters detailing his health, his surroundings, and his requests, acting as a factual reporter of his life in prison without focusing on her own feelings or conjectures about the future.', 'extras': {'signature': 'EnEKbwERTTIPBVV/Dxx2jEXGwJzRQ63o7yIo7mg+9M61FEyWEx+sAD5iQIpRRnggctj9sKzWB0aNl0rWG5H7LXvLDcQ8nO+ZxCOOe/IqdWFFLG0RTFd/FlupaL/LaxmJWZDeYhSaiwDh5CROaHD230wVCA=='}}]
======================================================================
Question 7/10
Who is Svidrigailov?

2026-08-22 22:10:39.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Generated answer:
[{'type': 'text', 'text': 'Based on the provided text, SvidrigaÃ¯lov is described by Raskolnikov as a "coarse brute," a "depraved sensualist," and a "blackguard." He is a man who always has some design or project, and he possesses an "original, even a mysterious character." The text also notes that he eventually shoots himself.', 'extras': {'signature': 'EnEKbwERTTIPIWgjbQRk0798eS/pvn/IHP8c87UgFu+heEBNYxHF+mcM/2GfoXwuXkoISvxe6C1mPJMCIYDQzjMyDj8wqjEjKayH88dXxJoWMl4KasUL6VSBE6ewYXplDZO2a/LdMxXKIcc3Y8e6pJg7sA=='}}]
======================================================================
Question 8/10
What is Raskolnikov's theory about extraordinary people?

2026-08-22 22:10:39.633 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Generated answer:
[{'type': 'text', 'text': 'I could not find enough information in the book to answer this question.', 'extras': {'signature': 'EnEKbwERTTIPM0EvfbEBV9ORv8OH3dKbMuAaGe/C4pQER6NqvjpGfsgV9GSlINi1y45nA+wtPyO+ltxcqPHO0cX1KlB9T+1VmXLS10LRrwVcnHC9LWRdEpCXh01VXlrb7EX1iWa8k3GbsvMNSlo1rbUtdw=='}}]
======================================================================
Question 9/10
Who was Alyona Ivanovna?

2026-08-22 22:10:40.187 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Generated answer:
[{'type': 'text', 'text': 'Alyona Ivanovna was a woman who lent money. According to the text, she was described by a student as being "as rich as a Jew" and someone from whom you could always get money.', 'extras': {'signature': 'EnEKbwERTTIPnM+YMQEeZAkLKFx91lEsslJ2lzXiqdwGbvu1d0SMCieHJOnx02qIKy/rY6hdaqJQSOEU8kaVdMtszK90TfX80kqYlXvbWKGg/8eI7wJSMRBK598jeJcN+cyQCiG1X1BxUjTUu/KaeIqiNw=='}}]
======================================================================
Question 10/10
How does Sonia influence Raskolnikov?

Generated answer:
[{'type': 'text', 'text': "I could not find enough information in the book to answer this question. The provided context focuses on Raskolnikov's interactions with Sonia regarding her personal sacrifices and her family's precarious situation, but it does not describe how Sonia influences him.", 'extras': {'signature': 'EnEKbwERTTIPQaCowztVc1MhaI0C8WF1ybF1Pyycw1CJd+/ZgyJzN/4KkQR/AeVIEoXoZQkSFNHa6Ka/WkxZNIaZfRf15fGRUoJm26LlnzPH5Zl3+qOkaqlGS2bNSAsiqOUQY/RscXnaOK3mKC44atH2Ew=='}}]


======================================================================
RAG EVALUATION DATASET
======================================================================
Successful samples: 10

Ragas dataset created successfully.
Features: ['user_input', 'retrieved_contexts', 'response', 'reference']


======================================================================
STARTING RAGAS EVALUATION
======================================================================

/tmp/ipykernel_1227/1448057119.py:236: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(llm)

Evaluating:   0%|          | 0/30 [00:00<?, ?it/s]

ERROR:ragas.executor:Exception raised in Job[2]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[10]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[13]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[14]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[16]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[17]: TimeoutError()

======================================================================
RAGAS RESULTS
======================================================================
{'context_recall': 0.0000, 'faithfulness': 0.8571, 'factual_correctness(mode=f1)': 0.1857}


======================================================================
PER-QUESTION RESULTS
======================================================================

,user_input,retrieved_contexts,response,reference,context_recall,faithfulness,factual_correctness(mode=f1)
0,Who is Raskolnikov?,[to know him?â€™\nâ€˜I â€¦ was acquainted â€¦ my siste...,"[{'type': 'text', 'text': 'I could not find en...",Rodion Raskolnikov is the central character of...,0.0,0.0,NaN
1,Who is Sonia Marmeladova?,"[as Sonia had just before. â€˜No, what has kept ...","[{'type': 'text', 'text': 'Sonia Marmeladova i...",Sonia Marmeladova is the daughter of Marmelado...,0.0,1.0,0.44
2,Why did Raskolnikov kill the old woman?,[and waited. Water was brought.\nâ€˜It was I â€¦â€™ ...,"[{'type': 'text', 'text': 'I could not find en...",Raskolnikov kills Alyona Ivanovna because he b...,0.0,1.0,0.00
3,Who is Porfiry Petrovich?,[least to control his overstrained nerves. At ...,"[{'type': 'text', 'text': 'Porfiry Petrovich i...",Porfiry Petrovich is the investigating magistr...,0.0,NaN,0.33
4,What happens to Raskolnikov at the end of the ...,[thought. He felt as though the fateful moment...,"[{'type': 'text', 'text': 'I could not find en...",Raskolnikov confesses to his crime and is sent...,0.0,NaN,NaN
5,What is the relationship between Sonia and Ras...,[her before and he had only roused it again.\n...,"[{'type': 'text', 'text': 'Based on the provid...",Sonia becomes closely connected to Raskolnikov...,0.0,NaN,NaN
6,Who is Svidrigailov?,[1Free eBooks at Planet eBook.com\nIntense d...,"[{'type': 'text', 'text': 'Based on the provid...",Arkady Svidrigailov is a wealthy and morally a...,0.0,1.0,0.00
7,What is Raskolnikov's theory about extraordina...,[TRANSLATORâ€™S NOTE.\nâ€˜But morality? And so to ...,"[{'type': 'text', 'text': 'I could not find en...",Raskolnikov's theory suggests that extraordina...,0.0,1.0,0.00
8,Who was Alyona Ivanovna?,[Ivanovna and give him her address. This of it...,"[{'type': 'text', 'text': 'Alyona Ivanovna was...",Alyona Ivanovna was an elderly pawnbroker whom...,0.0,1.0,0.33
9,How does Sonia influence Raskolnikov?,[her before and he had only roused it again.\n...,"[{'type': 'text', 'text': ""I could not find en...",Sonia influences Raskolnikov through her compa...,0.0,1.0,0.20

======================================================================
AVERAGE SCORES
======================================================================

                Average Score
context_recall       0.000000
faithfulness         0.857143

======================================================================
INTERPRETATION
======================================================================
context_recall: 0.000
  Poor performance. Investigate retrieval, chunking, prompts, or the LLM.
faithfulness: 0.857
  Good performance, but there is room for improvement.

Results saved to:/content/ragas_results.csv
Test dataset saved to:/content/ragas_test_dataset.json


======================================================================
STEP 4 COMPLETED
======================================================================

Your Crime and Punishment RAG application has now been
evaluated using Ragas.

Metrics evaluated:

1. Context Recall
   -> Did retrieval find the information needed?

2. Faithfulness
   -> Is the generated answer supported by the retrieved
      book context?

3. Factual Correctness
   -> Is the generated answer factually consistent with
      the expected/reference answer?

Use the scores to decide what to improve next:
- chunk size
- chunk overlap
- number of retrieved documents (k)
- embedding model
- prompt
- Gemini temperature
- retrieval strategy